---
- name: Reboot all nodes
  hosts: hosts
  gather_facts: False
  vars_files:
    - ardana_net_vars.yml
    - vars/main.yml

  tasks:

  - include: _get_ansible_hosts.yml

  - name: Turn off the Keystone Fernet Token-Signing Key Rotation
    shell: |
      ansible-playbook -vvv -i hosts/verb_hosts keystone-stop-fernet-auto-rotation.yml
    args:
      chdir: /var/lib/ardana/scratch/ansible/next/ardana/ansible
    become: true
    become_user: ardana

  - name: Reboot deployer node
    include: reboot-node.yml
    vars:
      ansible_node: "{{ ardana_ansible_deployer }}"
      node_is_deployer: true

  - name: Reboot controller nodes
    include: reboot-node.yml
    vars:
      ansible_node: "{{ item }}"
      node_is_deployer: false
    when: item != ardana_ansible_deployer
    with_items: "{{ ardana_ansible_controllers }}"

  - name: Reboot remaining nodes
    include: reboot-node.yml
    vars:
      ansible_node: "{{ item }}"
      node_is_deployer: false
    when: item != ardana_ansible_deployer and
          item not in ardana_ansible_controllers
    with_items: "{{ ardana_ansible_nodes }}"

  - name: Run a global service status check
    shell: |
      ansible-playbook -vvv -i hosts/verb_hosts ardana-status.yml
    args:
      chdir: /var/lib/ardana/scratch/ansible/next/ardana/ansible
    become: true
    become_user: ardana

