---

- import_playbook: _create-vcloud-inventory.yml

- name: Disable DHCP on the cloud infra management network
  hosts: localhost
  connection: local
  tasks:
    - name: Disable DHCP on the cloud infra management network
      command: |
        openstack --os-cloud {{ os_cloud }} subnet set \
          --no-dhcp \
          openstack-ardana-{{ cloud_env }}_management_subnet

- name: Register crowbar cloud nodes
  hosts: cloud_virt_hosts
  any_errors_fatal: true
  remote_user: root
  gather_facts: True
  vars:
    task: "register"
    ansible_ssh_common_args: >
      -o ProxyCommand='ssh -o UserKnownHostsFile=/dev/null -o
      StrictHostKeyChecking=no -W %h:%p -q root@{{ hostvars[cloud_env].ansible_host }}'
      -o ControlPath='~/.ansible/cp/{{ cloud_env }}-%r@%h:%p'

  tasks:
    - block:
        - include_role:
            name: crowbar_register
        - include_role:
            name: crowbar_setup
          vars:
            qa_crowbarsetup_cmd: "onadmin_{{ command }}"
          loop:
            - allocate
            - waitcloud
            - post_allocate
            - setup_aliases
          loop_control:
            loop_var: command

      rescue:
        - include_role:
            name: rocketchat_notify
          delegate_to: "{{ cloud_env }}"
          vars:
            rc_action: "finished"
            rc_state: "Failed"
          when: rc_notify

        - name: Stop if something failed
          fail:
            msg: "{{ task }} failed."
