#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: Prepare first time admin node access
  hosts: "localhost"
  gather_facts: false
  vars:
    task: "deploy"

  tasks:
    - block:
        - name: Get vcloud node(s) IP(s) when heat output not available and virtual deploy
          command: |
             openstack --os-cloud "{{ os_cloud }}" stack output show {{ heat_stack_name }} {{ item }} -c output_value -f value
          loop: "{{ cli_stack_queries }}"
          register: "os_stack_output"
          when:
            - not is_physical_deploy
            - heat_stack_output is not defined

        - name: Store vcloud IP(s) when virtual deploy
          set_fact:
            "{{ item.item | replace('-', '_') }}": "{{ (item.stdout == 'None') | ternary([], item.stdout | from_yaml) }}"
            cacheable: True
          loop: "{{ (heat_stack_output is defined) | ternary(heat_stack_output_queries, os_stack_output.results) }}"
          loop_control:
            label: "{{ item.item | replace('-', '_') }}: {{ ('stdout' in item and item.stdout == 'None') | ternary([], item.stdout | default('') | from_yaml) }}"
          when: not is_physical_deploy

        - name: Clean up previously generated inventory file entries
          blockinfile:
            path: "inventory"
            insertafter: "\\[{{ item }}\\]"
            marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
          loop:
            - admin_virt
            - controllers_virt
            - computes_virt
            - crowbar:children
            - ardana:children
            - crowbar_virt:children
            - ardana_virt:children
            - crowbar_qe:children
            - ardana_qe:children

        - name: Add admin host on ansible inventory file when virtual deploy
          blockinfile:
            path: "inventory"
            insertafter: "\\[admin_virt\\]"
            marker: "# {mark} ANSIBLE MANAGED BLOCK admin_virt"
            block: |
              {{ cloud_env }}      ansible_host={{ admin_floating_ip }}
          when: not is_physical_deploy

        - name: Populate the ansible {{ cloud_product }} inventory group
          blockinfile:
            path: "inventory"
            insertafter: "\\[{{ cloud_product }}:children\\]"
            marker: "# {mark} ANSIBLE MANAGED BLOCK {{ cloud_product }}:children"
            block: |
              {{ cloud_env }}

        - name: Populate the ansible {{ cloud_product }}_virt inventory group
          blockinfile:
            path: "inventory"
            insertafter: "\\[{{ cloud_product }}_virt:children\\]"
            marker: "# {mark} ANSIBLE MANAGED BLOCK {{ cloud_product }}_virt:children"
            block: |
              {{ cloud_env }}
          when: not is_physical_deploy

        - name: Populate the ansible {{ cloud_product }}_qe inventory group
          blockinfile:
            path: "inventory"
            insertafter: "\\[{{ cloud_product }}_qe:children\\]"
            marker: "# {mark} ANSIBLE MANAGED BLOCK {{ cloud_product }}_qe:children"
            block: |
              {{ cloud_env }}
          when: is_physical_deploy

        - name: Create temp inventory with all non-admin virtual nodes
          hosts: "{{ cloud_env }}"
          gather_facts: False
          vars:
            virtual_hosts:
              - group: controller
                ips: "{{ hostvars['localhost'].controller_conf_ips | difference([hostvars['localhost'].admin_conf_ip]) }}"
              - group: compute
                ips: "{{ hostvars['localhost'].compute_conf_ips }}"

          tasks:
            - name: Create temp inventory with all non-admin virtual nodes
              add_host:
                name: "{{ item.0.group }}{{ item.0.ips.index(item.1) + 1 }}"
                ansible_host: "{{ item.1 }}"
                ansible_password: "linux"
                group: "{{ item.0.group }}, cloud_virt_hosts"
                ansible_ssh_common_args: >
                  -o ProxyCommand='ssh -o UserKnownHostsFile=/dev/null -o
                  StrictHostKeyChecking=no -W %h:%p -q root@{{ hostvars[cloud_env].ansible_host }}'
                  -o ControlPath='~/.ansible/cp/{{ cloud_env }}-%r@%h:%p'
              loop: "{{ virtual_hosts | subelements('ips') }}"
              loop_control:
                label: "{{ item.0.group }}{{ item.0.ips.index(item.1) + 1 }} - {{ item.1 }}"


        - name: Configure first time admin node access
          add_host:
            name: "{{ cloud_env }}"
            ansible_host: "{{ is_physical_deploy | ternary(omit, admin_floating_ip) }}"
            ansible_password: "linux"
      rescue:
        - include_role:
            name: rocketchat_notify
          vars:
            rc_action: "finished"
            rc_state: "Failed"
          when: rc_notify

        - name: Stop if something failed
          fail:
            msg: "{{ task }} failed."


- name: Ensure public keys on admin node
  hosts: "{{ cloud_env }}"
  remote_user: root
  # NOTE: don't gather facts before admin node becomes accessible
  gather_facts: false
  vars:
    task: "deploy"

  tasks:
    - block:
        - name: Wait for admin node to be accessible
          wait_for_connection:
            sleep: 10
            timeout: 300

        - name: Gather facts
          setup:

        - include_role:
            name: ssh_keys
      rescue:
        - include_role:
            name: rocketchat_notify
          vars:
            rc_action: "finished"
            rc_state: "Failed"
          when: rc_notify

        - name: Stop if something failed
          fail:
            msg: "{{ task }} failed."
