---
  product:
    version: 2

  baremetal:
    subnet: 192.168.245.0
    netmask: 255.255.255.0

  servers:

    - id: cp1-0001
      ip-addr: {{ controller_mgmt_ips[0] }}
      role: STD-CONTROLLER-ROLE
      server-group: RACK1
      mac-addr: b2:72:8d:ac:7c:6f
      ilo-ip: 192.168.109.3
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT

    - id: cp1-0002
      ip-addr: {{ controller_mgmt_ips[1] }}
      role: STD-CONTROLLER-ROLE
      server-group: RACK2
      mac-addr: 8a:8e:64:55:43:76
      ilo-ip: 192.168.109.4
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT

    - id: cp1-0003
      ip-addr: {{ controller_mgmt_ips[2] }}
      role: STD-CONTROLLER-ROLE
      server-group: RACK3
      mac-addr: 26:67:3e:49:5a:a7
      ilo-ip: 192.168.109.5
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT

    - id: cm1-0001
      ip-addr: {{ compute_mgmt_ips[0] }}
      role: STD-COMPUTE-ROLE
      server-group: RACK1
      mac-addr: d6:70:c1:36:43:f7
      ilo-ip: 192.168.109.6
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT
