heat_template_version: 2016-10-14

description: >
  Template for deploying Ardana in a multinode setup

parameters:
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
    default: engcloud-cloud-ci
  image_id_controller:
    type: string
    label: Image ID
    description: Image to be used for compute instance (controller)
    default: cleanvm-jeos-SLE12SP3
  instance_type_controller:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used for the controller
    default: cloud-ardana-job-controller
  index:
    type: number
    description: controller index suffix
    default: 1

  networks:
    type: json
    description: Networks to configure on controller

resources:
  controller:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: controller$index
          params:
            $index: {get_param: index}
      key_name: { get_param: key_name }
      image: { get_param: image_id_controller }
      flavor: { get_param: instance_type_controller }
      networks: { get_param: networks }

  # disks
  controller_vdb:
    type: OS::Cinder::Volume
    properties:
      size: 30
  controller_vdc:
    type: OS::Cinder::Volume
    properties:
      size: 30
  controller_vdd:
    type: OS::Cinder::Volume
    properties:
      size: 30
  controller_vde:
    type: OS::Cinder::Volume
    properties:
      size: 30
  controller_vdf:
    type: OS::Cinder::Volume
    properties:
      size: 30


  controller_vol_att_vdb:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: controller }
      volume_id: { get_resource: controller_vdb }
      mountpoint: /dev/vdb
  controller_vol_att_vdc:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: controller }
      volume_id: { get_resource: controller_vdc }
      mountpoint: /dev/vdc
  controller_vol_att_vdd:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: controller }
      volume_id: { get_resource: controller_vdd }
      mountpoint: /dev/vdd
  controller_vol_att_vde:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: controller }
      volume_id: { get_resource: controller_vde }
      mountpoint: /dev/vde
  controller_vol_att_vdf:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: controller }
      volume_id: { get_resource: controller_vdf }
      mountpoint: /dev/vdf

outputs:
  # networks
  networks:
    description: networks
    value: { get_attr: [ controller, networks] }
  # addresses
  addresses:
    description: addresses
    value: { get_attr: [ controller, addresses] }
