---
- name: Sync automation scripts onto the admin node
  synchronize:
    src: "{{ automation_scripts_path }}"
    dest: "{{ admin_scripts_path }}"
    delete: yes
    recursive: yes

- name: Copy generated mkcloud.config to admin node
  copy:
    src: "{{ mkcloud_config_file }}"
    dest: "{{ admin_mkcloud_config_file }}"

- name: Crowbar log stream at
  debug:
    msg: "http://{{ ansible_host }}:9091/"

- name: Run qa_crowbarsetup.sh command on the admin node
  shell: |
    . {{ admin_scripts_path }}/qa_crowbarsetup.sh
    {{ qa_crowbarsetup_cmd }} 2>&1 | tee -a {{ qa_crowbarsetup_log }}
    exit ${PIPESTATUS[0]}
  args:
    executable: "/bin/bash"

