---

interface_models:
  - name: ALL
    service_groups:
      - admin
      - controller
      - compute
    network_interfaces:
      - network_groups:
          - MANAGEMENT
          - PUBLIC
          - OS_SDN
          - STORAGE
