
admin_scripts_path: "/root/scripts"

admin_mkcloud_config_file: "/root/mkcloud.config"
admin_crowbar_batch_file: "/root/scenario.yml"
qa_crowbarsetup_log: "/root/qa_crowbarsetup.log"

cloud_fqdn: "{{ cloud_env }}.prv.suse.net"

mkcloud_config_file: "{{ workspace_path }}/mkcloud.config"
crowbar_batch_file: "{{ workspace_path }}/scenario.yml"

ssl_enabled: true
